<div class="form_container">
    <form action="<?php echo BASE_URL.'/ticket/addticket'; ?>" method="post">
        <fieldset class="fieldset">
            <legend>Maintain a list of boarding passes</legend>
            <div class="container_tikets_input">
                <div class="ticket_container" id="ticket_container">
                    <?php foreach($this->getPropertiesTicket() as $property => $propertyTytle): ?>
                        <div class="property">
                            <label  title="<?php echo $propertyTytle; ?>"><p><?php echo $propertyTytle; ?></p></label>
                            <div class="input">
                                <?php if($property == 'type_transport'): ?>
                                    <select name="tickets[<?php echo $property; ?>][]">
                                        <?php foreach($this->getTypeTransport() as $value => $title ): ?>
                                            <option value="<?php echo $value ?>"><?php echo $title ?></option>
                                        <?php endforeach; ?>
                                    </select>
                                <?php else: ?>
                                    <input name="tickets[<?php echo $property; ?>][]">
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <div class="add_ticket" id="add_ticket" title="Add ticket"><span>+</span></div>
            <div class="button_form">
                <button type="submit" title="Submit">Submit</button>
            </div>
        </fieldset>
    </form>
</div>