<div class="footer_container">
    <div class="contact_list">
        <ul>
            <li>
                <p>Dmitriy Datsenko:</p>
            </li>
            <li>
                <p><a href="mailto:info@lotrans.info">info@lotrans.info</a></p>
            </li>
            <li>
                <p>Skype: dacenko_dmitriy</p>
            </li>
            <li>
                <p>phone: +38 (050) 614 17 11</p>
            </li>
        </ul>
    </div>
</div>