<div class="header_container">
    <div class="logo">
        <a href="<?php echo BASE_URL ?>"><h1>Trip sorter</h1></a>
    </div>
    <div class="menu_container">
        <ul>
            <li>
                <button class="button" onclick="window.location='<?php echo BASE_URL.'/ticket/' ?>'">
                    <span>Maintain a list of boarding passes</span>
                </button>
            </li>
            <li>
                <button class="button" onclick="window.location='<?php echo BASE_URL.'/ticket/sorted' ?>'">
                    <span>Sorted list of boarding passes</span>
                </button>
            </li>
            <li>
                <button class="button" onclick="window.location='<?php echo BASE_URL.'/ticket/notsorted' ?>'">
                    <span>Not all sorted list of boarding passes</span>
                </button>
            </li>
        </ul>
    </div>
</div>