<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Trip sorter</title>
    <?php if($this->isRedirect()): ?>
        <meta http-equiv="refresh" content="0; url=<?php echo $this->getRedirect(); ?>" >
    <?php else: ?>
        <?php foreach($this->getCss() as $css):?>
             <link rel="stylesheet" type="text/css" href="<?php echo $css ?>" media="all">
        <?php endforeach; ?>
        <?php foreach($this->getJs() as $js): ?>
            <script type="text/javascript" src="<?php echo $js ?>"></script>
        <?php endforeach; ?>
    <?php endif; ?>
</head>